site_name: ""
site_url: https://testnet.productscience.ai/
repo_url: https://testnet.productscience.ai/
edit_uri: edit/main/docs
copyright: Copyright ProductScience Inc. All rights reserved.
site_description: >-
  Learn to configure and use "Stealth-mode blockchain project"

# Content
nav:
  - Docs:
      - Introduction: introduction.md
      - Quickstart:
          - Developer: 
              - Quickstart: quickstart/developer/quickstart.md
          - Participant:
              - Quickstart: quickstart/participant/quickstart.md
              - Multiple nodes: quickstart/participant/multiple-nodes.md
              - Migrate: quickstart/participant/migrate.md
              - Network Node API: quickstart/participant/network-node-api.md
      - Wallet & Transfer Guide: wallet-and-transfer-guide.md
      - Pricing: pricing.md
      - Terms & Policies: termsofuse.md
      - Hardware Specifications: hardware-specifications.md
      - Transactions & Governance: transactions-and-governance.md
      - Help: help.md
  - API Reference:
     - API Reference: api-reference/api-reference.md
     - REST API: api-reference/rest-api.md

# Visual
theme:
  name: material
  custom_dir: overrides
  favicon: images/Icon.png
  font:
    text: Manrope
  palette:
    # Light mode
    # media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  include_search_page: false
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.tabs.link        # linkable content tabs
    - navigation.indexes
    - navigation.tracking
    - navigation.instant       # faster page loads (instant loading)
    - search.suggest
    - toc.integrate            # table of contents inside page

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - toc
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true    # GitHub-style checkboxes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

plugins:
  - minify:
      minify_html: false
  - search
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: true
      css_style:
        width: "50%"

extra_javascript:
  - buttons.js

/* Подсветка строки при наведении */
.highlighttable td.code span[class^="__span-"]:hover {
  background-color: rgba(255, 255, 0, 0.07); /* лёгкая подсветка */
  display: block;
}

/* Убираем разрывы между строками и номерами */
.highlighttable td.code > div.highlight {
  margin-left: 0 !important;
}

.highlighttable td.code span[class^="__span-"] {
  display: block;
  padding-left: 0;      /* выравнивание по левому краю */
  margin: 0;
  line-height: 1.5;
}
